### ISSUE TITLE
Nitrux OS Installer window should maximize automatically.  Widget should look like maximize widget.

### ISSUE THREAD

**Issue by wpostma** [Nitrux/nxs#1]
I am trying out Nitrux live CD image from which a user launches the installer when you want to install.  From within a virtual machine, or on a physical PC with a resolution of around 1280x1024 or less, the installer appearance is marred by not being maximized. You can see in the screenshot that a user can't see the Next button because it's off the bottom of either the physical monitor, or the virtual screen if it is being installed into a virtual machine.

Exacerbating the confusion is that it's possible to manually maximize this installer (which is odd since most installers just take over and always go kiosk mode and hide the desktop), but the installer window's maximize widget looks unlike anything I've ever seen. It would be more user friendly to just go full screen and then show a reasonable icon that means "exit fullscreen" if you mouse hover over the top right corner.  The usual icon for this is:

http://fontawesome.io/3.2.1/icon/fullscreen/

The installer showing the cropped (nearly invisible) Next button (due to default window height being taller than my vmware vm screen resolution):

![installer_on_live_image_should_be_maximized_or_should_be_smaller_by_default](https://user-images.githubusercontent.com/1833470/35451862-7eb36756-0279-11e8-88ee-13d8da2b835f.png)

Installers are uniquely constrained environments. You may notice that assumptions on minimum screen resolution need to be quite conservatively assessed when building installers. These days even physical hardware is not the only consideration. Most users will try Nitrux first from inside a virtual machine or hyperviser system, such as qemu/kvm, vmware, virtualbox, etc.

Nice installer by the way.

**Comment by wpostma** [comment]
After the first installation, the system boots to a black screen with a full screen keyboard. This is probably not intentional. Clicking on the full screen onscreen keyboard (appears to be for tablet access) will reveal a greeter screen with username and password input boxes.  This is an extremely odd decision.

Even odder, while it seems some effort to be tablet-friendly has been made this has resulted in Nitrux being unusable from a virtual machine with a keyboard and a mouse.

Complete inability to focus and type into the password box WITH A KEYBOARD is a surprising move on your installer.
  
Thus ends my attempt to learn about Nitrux OS. It's not ready to log into yet:

![the_what](https://user-images.githubusercontent.com/1833470/35452232-ba0d96a4-027a-11e8-8e8c-dccc6d9fb200.png)


The above picture could be explained by the video driver in the linux kernel doing something odd here.

**Comment by wpostma** [comment]
After 15 minutes I managed to log into the login screen. Note that VMWare Workstation Player does not offer me any way to experiment with alternative video.   lspci reports
VGA compatible controller: VMware SVGA II Adapter as my video card type from inside Nitrux.

If there's somewhere ELSE I should log a but about a posssible bug with your Linux 4.13 kernel, plus this video card type, when used with your QT+Nomad desktop, LMK and I'll log a second bug and provide any details to reproduce.

**Comment by luis-lavaire** [comment]
Hi, @wpostma. Thanks for your feedback. The OS installer isn't hosted here (this repository is for an AppImage command-line installer), but we will take into account this anyway.
Please reopen this issue on https://github.com/nomad-desktop/calamares-settings-nxos. That's the place for it. Cheers.

**Comment by wpostma** [comment]
thanks, relogged here:

https://github.com/nomad-desktop/calamares-settings-nxos/issues/4

**Comment by luis-lavaire** [comment]
You are welcome.
